//
//  Guest.swift
//  ZooInformationSystem
//
//  Created by Jessie Ann Griffin on 10/24/20.
//

import Foundation

class Guest {

    private var name: String // customer full name
    private var address: String
    private var id: UUID // autogenerated database ID
    private var seasonPass: Bool // whether the guest has a season pass
    private var billingInfo: String
    private var reservation: Event // This was missing from the original assignment

    init(name: String,
         address: String,
         id: UUID = UUID(),
         seasonPass: Bool,
         billingInfo: String,
         reservation: Event) {

        self.name = name
        self.address = address
        self.id = id
        self.seasonPass = seasonPass
        self.billingInfo = billingInfo
        self.reservation = reservation
    }

    func scheduleVisit() {
        print("Guest: \(name) is scheduled to visit on \(reservation.getDay())")
    }

    func addToCart() {
        print("Added to cart")
    }

    func registerGuest() {
        print("Guest: \(name) has been registered for an event on \(reservation.getDay())")
    }
}
